[package]
name = "d2statfind"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "0.4.24"
num_enum = "0.6.0"
reqwest = "0.11.16"
rustgie = { git = "https://github.com/BarmonHammer/rustgie.git", rev = "6b8c748" }
serde = { version = "1.0.160", features = ["derive"] }
tokio = { version = "1.27.0", features = ["full"] }
